### PR TITLE
Type error fix

### LINKED ISSUE #212: Type error after updatin to Angular 15
I'm getting following errors after updating to Angular 15:
```
Error: node_modules/@ngx-resource/core/lib/Declarations.d.ts:110:125 - error TS2344: Type 'O' does not satisfy the constraint '{}'.

110 export interface IResourceMethodResultStrict<IB, IQ, IP, O> extends IResourceMethodStrictBase<IB, IQ, IP, O, ResourceResult<O>> {

  node_modules/@ngx-resource/core/lib/Declarations.d.ts:110:58
    110 export interface IResourceMethodResultStrict<IB, IQ, IP, O> extends IResourceMethodStrictBase<IB, IQ, IP, O, ResourceResult<O>> {
    This type parameter might need an `extends {}` constraint.

Error: node_modules/@ngx-resource/core/lib/Declarations.d.ts:112:97 - error TS2344: Type 'O' does not satisfy the constraint '{}'.

112 export interface IResourceMethodResult<IB, O> extends IResourceMethodBase<IB, O, ResourceResult<O>> {

  node_modules/@ngx-resource/core/lib/Declarations.d.ts:112:44
    112 export interface IResourceMethodResult<IB, O> extends IResourceMethodBase<IB, O, ResourceResult<O>> {
    This type parameter might need an `extends {}` constraint.
```

Most likely this is because of typescript version changed on that Angular release. Any idea how to solve this issue?

### PR DESCRIPTION
**Pull request by tarlepp**
Fixes #212

### CODE REVIEW

**Comment by Wolfien77** [comment]
Tested and confirmed working with Angular 15.1.0

**Comment by Wolfien77** [comment]
Can this change be pushed to npm?

**Comment by tarlepp** [comment]
There might be some issues with that #212 with earlier Angular versions (not sure about that) - but it might be use case because this library current version supports Angular `10.x` which is EOL - so to be safe I would upgrade those angular dependencies to latest and then create new major version of this library.

Or check that support for all those versions between 10.x and 15.x + typescript versions etc. and make solution that works on all of those use cases - personally I think this would be the "correct" solution - if this library has been updated those angular versions regularly - now that is not the use case.

So I would just release new major version of this library which contains necessary fixes for angular 15.x

And also seems like this repository is not so active, so maybe there is someone or multiple persons who wants to continue to maintain this library - WDYT?

**Comment by troyanskiy** [comment]
Hello @tarlepp 
Thank you for the PR.
New versions are published in NPM. Only `core` and `handler-ngx-http`.
CC: @Wolfien77
