### ISSUE TITLE
returnInternal.$observable.publish is not a function

### ISSUE THREAD

**Issue by namlehong** [troyanskiy/ngx-resource#113]
after upgrade to 3.0 i face this issue for just practice simple resource like document mention

**Comment by troyanskiy** [comment]
Hello.
Could you please try updated version 3.0.1
Thanks for the issue

**Comment by namlehong** [comment]
yeap, the problem was gone away.

**Comment by troyanskiy** [comment]
great.
Thanks again for the issue.

**Comment by zaidakram** [comment]
Was facing the same issue. Upgrading to 3.0.1 worked for me. Thanks
